@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

hide stereotype

Person(user, "App user")
Person(phone, "Phone")

System_Boundary(dird_system, "Directory") {
    Container(dird_app, "wazo-dird", "Python", "Directory service")
    Container(auth, "wazo-auth", "Python", "Authentication service") [["/overview/authentication.html"]]
    ContainerDb(pgsql, "PostgreSQL", "C", "Database")
    Container(bus, "RabbitMQ", "Erlang", "Message bus")
    Container(agid, "xivo-agid", "Python", "AGI service")
    Container(asterisk, "Asterisk", "C", "Media server")
    Container(dird_phoned, "wazo-dird-phoned", "Python", "Phone directory proxy service")
}

Container_Boundary(extern, "Sources") {
    Container(confd, "wazo-confd", "Python", "Configuration service") [["/overview/configuration.html"]]
    System_Ext(ldap, "LDAP server")
    System_Ext(google, "Google")
    System_Ext(microsoft, "Microsoft Office 365")
}

' Relationships

' Services
Rel_U(dird_app, auth, " ", "REST")
Rel_L(dird_phoned, dird_app, " ", "REST")
Rel_R(agid, dird_app, " ", "REST")
Rel_R(asterisk, agid, " ", "AGI")
Rel_D(dird_app, pgsql, " ", "SQL")
Rel_D(dird_app, bus, " ", "AMQP")
' Layout corrections
Lay_R(pgsql, microsoft)
Lay_L(dird_phoned, dird_app)
Lay_L(agid, dird_app)
Lay_L(agid, asterisk)
Lay_D(agid, dird_phoned)

' Sources
Rel_L(dird_app, confd, " ", "REST")
Rel_L(dird_app, ldap, " ", "LDAP")
Rel_L(dird_app, google, " ", "REST")
Rel_L(dird_app, microsoft, " ", "REST")
' Layout corrections
Lay_D(confd, ldap)
Lay_D(ldap, google)
Lay_D(google, microsoft)

' User
Rel_R(user, dird_app, " ", "REST")
' Layout corrections
Lay_D(user, phone)

' Phone
Rel_D(phone, asterisk, " ", "SIP/SCCP")
Rel_R(phone, dird_phoned, " ", "REST")

@enduml
