@startuml
!include C4_Container.puml

hide stereotype

System_Boundary(wazo_platform, "Wazo Platform"){
    Container(webhookd, "wazo-webhookd", "Python", "Webhook service")
    Container(db, "Postgresql", "C", "Database")
    Container(bus, "RabbitMQ", "Erlang", "Messaging Bus")
    Container(auth, "wazo-auth", "Python", "Authentication service") [["../documentation/overview/authentication.html"]]
}

System_Ext(external_push_server, "Supported push message service (e.g. FCM, APNS)", "HTTP")
actor MobileUser

Rel_R(MobileUser, wazo_platform, "Logs in through mobile app", "REST")

Rel_U(webhookd, db, "SQL(store subscriptions)", "SQL")
Rel_D(bus, webhookd, "Relays Wazo platform events", "AMQP")

Rel_U(auth, bus, "generates user login events", "AMQP")
Rel_D(webhookd, external_push_server, "Sends push notifications", "HTTP")
' Rel_L(auth,webhookd,"Notify of login events (through bus)", "async,AMQP", $tags="virtual")

auth .LEFT.> webhookd : ===Notify of user login events\n(through bus)

Rel_U(external_push_server, MobileUser, "Relays push notifications")

@enduml
