import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/* The UC documentation lives in its own docs plugin instance, so crossing from
   /docs to /uc-doc swaps the whole sidebar. This one repeats the four
   top-level entries of docsSidebar -- with the UC tree expanded for real and
   the /docs entries as links -- so the menu keeps its shape either side of the
   jump. The root index doc is the category's own link; the plugin's
   sidebarItemsGenerator drops it from the autogenerated items so it is not
   listed twice. */
const sidebars: SidebarsConfig = {
  ucDocSidebar: [
    { type: 'link', href: '/docs/intro', label: 'Introduction' },
    {
      type: 'category',
      label: 'UC Documentation',
      collapsed: false,
      link: { type: 'doc', id: 'index' },
      items: [{ type: 'autogenerated', dirName: '.' }],
    },
    { type: 'link', href: '/docs/category/tutorials', label: 'Tutorials' },
    { type: 'link', href: '/docs/category/contribute', label: 'Contribute' },
  ],
};

export default sidebars;
