import fs from 'node:fs';
import path from 'node:path';

import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import matter from 'gray-matter';

type SidebarItem = Extract<SidebarsConfig[string], unknown[]>[number];

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const UC_DOC_DIR = path.join(__dirname, 'uc-doc');

type Meta = { label: string; position: number };
type TreeEntry = { name: string; position: number; item: SidebarItem };

const readMeta = (source: string, fallback: string): Meta => {
  if (!fs.existsSync(source)) {
    return { label: fallback, position: Number.POSITIVE_INFINITY };
  }
  const { data } = matter(fs.readFileSync(source, 'utf8'));
  return {
    label: data.sidebar_label ?? data.title ?? fallback,
    position: data.sidebar_position ?? Number.POSITIVE_INFINITY,
  };
};

/* The UC documentation is a second docs plugin instance (routeBasePath
   /uc-doc) and a sidebar can only reference docs from its own instance, so
   this sidebar mirrors its whole tree with plain links, read off the
   filesystem rather than hardcoded. A category's `link` is likewise limited to
   its own instance, so a folder's landing page travels in customProps and
   src/theme/DocSidebarItem/Category turns it back into a clickable header --
   the same shape sidebarsUcDoc.ts renders natively on the /uc-doc side. */
const ucDocTree = (dir: string, baseHref: string): SidebarItem[] =>
  fs
    .readdirSync(dir, { withFileTypes: true })
    .flatMap((entry): TreeEntry[] => {
      const name = entry.name.replace(/\.md$/, '');
      const href = `${baseHref}/${name}`;

      if (entry.isDirectory()) {
        const meta = readMeta(path.join(dir, entry.name, 'index.md'), name);
        const children = ucDocTree(path.join(dir, entry.name), href);
        // a folder holding nothing but its own landing page has nothing to
        // expand -- the autogenerated sidebar renders those as a plain doc too
        const item: SidebarItem = children.length
          ? {
              type: 'category',
              label: meta.label,
              customProps: { href },
              items: children,
            }
          : { type: 'link', href, label: meta.label };
        return [{ name, position: meta.position, item }];
      }

      // the enclosing folder's landing page, carried by its category header
      if (!entry.name.endsWith('.md') || entry.name === 'index.md') {
        return [];
      }

      const meta = readMeta(path.join(dir, entry.name), name);
      const item: SidebarItem = { type: 'link', href, label: meta.label };
      return [{ name, position: meta.position, item }];
    })
    // same ordering as the autogenerated sidebar: sidebar_position first,
    // then alphabetically on the file/folder name
    .sort((a, b) => a.position - b.position || a.name.localeCompare(b.name))
    .map((entry) => entry.item);

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'UC Documentation',
      customProps: { href: '/uc-doc' },
      items: ucDocTree(UC_DOC_DIR, '/uc-doc'),
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'generated-index',
        description:
          'Learn how to leverage the power of the platform to build your own applications.',
      },
      items: [{ type: 'autogenerated', dirName: 'tutorials' }],
    },
    {
      type: 'category',
      label: 'Contribute',
      link: {
        type: 'generated-index',
        description:
          'There are many ways to contribute to the project. Find out how you can help!',
      },
      items: [{ type: 'autogenerated', dirName: 'contribute' }],
    },
  ],
};

export default sidebars;
