import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'link',
      href: '/uc-doc',
      label: 'UC Documentation',
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'generated-index',
        description:
          'Learn how to leverage the power of the platform to build your own applications.',
      },
      items: [{ type: 'autogenerated', dirName: 'tutorials' }],
    },
    {
      type: 'category',
      label: 'Contribute',
      link: {
        type: 'generated-index',
        description:
          'There are many ways to contribute to the project. Find out how you can help!',
      },
      items: [{ type: 'autogenerated', dirName: 'contribute' }],
    },
  ],
};

export default sidebars;
