import fs from 'node:fs';
import path from 'node:path';

import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';
import yaml from 'js-yaml';

type SidebarItem = Extract<SidebarsConfig[string], unknown[]>[number];

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

const UC_DOC_DIR = path.join(__dirname, 'uc-doc');
const UC_DOC_BASE = '/uc-doc';
const FRONT_MATTER = /^---\r?\n([\s\S]*?)\r?\n---/;

type FrontMatter = Record<string, unknown>;
type Meta = { label: string; position: number; slug?: string };
type TreeEntry = { name: string; position: number; item: SidebarItem };

const readMeta = (source: string, fallback: string): Meta => {
  const raw = fs.existsSync(source) ? fs.readFileSync(source, 'utf8') : '';
  const matched = FRONT_MATTER.exec(raw);
  const data = (matched ? yaml.load(matched[1]) : {}) as FrontMatter;
  return {
    label: String(data.sidebar_label ?? data.title ?? fallback),
    position: Number(data.sidebar_position ?? Number.POSITIVE_INFINITY),
    slug: typeof data.slug === 'string' ? data.slug : undefined,
  };
};

/* `slug` front matter moves one doc off its filesystem path -- uc-doc's only
   one today is upgrade/archives, served at /uc-doc/archives -- while its
   children stay where the folders put them. An absolute slug is rooted at the
   plugin's routeBasePath, a relative one at the containing folder. */
const hrefOf = (meta: Meta, baseHref: string, name: string) => {
  if (!meta.slug) {
    return `${baseHref}/${name}`;
  }
  return meta.slug.startsWith('/')
    ? `${UC_DOC_BASE}${meta.slug}`
    : `${baseHref}/${meta.slug}`;
};

/* The UC documentation is a second docs plugin instance (routeBasePath
   /uc-doc) and a sidebar can only reference docs from its own instance, so
   this sidebar mirrors its whole tree with plain links, read off the
   filesystem rather than hardcoded. A category's `link` is likewise limited to
   its own instance, so a folder's landing page travels in customProps and
   src/theme/DocSidebarItem/Category turns it back into a clickable header --
   the same shape sidebarsUcDoc.ts renders natively on the /uc-doc side. */
const ucDocTree = (dir: string, baseHref: string): SidebarItem[] =>
  fs
    .readdirSync(dir, { withFileTypes: true })
    .flatMap((entry): TreeEntry[] => {
      const name = entry.name.replace(/\.md$/, '');

      if (entry.isDirectory()) {
        const meta = readMeta(path.join(dir, entry.name, 'index.md'), name);
        const href = hrefOf(meta, baseHref, name);
        // the children keep the folder path even when the index is slugged
        const children = ucDocTree(
          path.join(dir, entry.name),
          `${baseHref}/${name}`,
        );
        // a folder holding nothing but its own landing page has nothing to
        // expand -- the autogenerated sidebar renders those as a plain doc too
        const item: SidebarItem = children.length
          ? {
              type: 'category',
              label: meta.label,
              customProps: { href },
              items: children,
            }
          : { type: 'link', href, label: meta.label };
        return [{ name, position: meta.position, item }];
      }

      // the enclosing folder's landing page, carried by its category header
      if (!entry.name.endsWith('.md') || entry.name === 'index.md') {
        return [];
      }

      const meta = readMeta(path.join(dir, entry.name), name);
      const item: SidebarItem = {
        type: 'link',
        href: hrefOf(meta, baseHref, name),
        label: meta.label,
      };
      return [{ name, position: meta.position, item }];
    })
    // same ordering as the autogenerated sidebar: sidebar_position first,
    // then alphabetically on the file/folder name
    .sort((a, b) => a.position - b.position || a.name.localeCompare(b.name))
    .map((entry) => entry.item);

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'UC Documentation',
      customProps: { href: UC_DOC_BASE },
      items: ucDocTree(UC_DOC_DIR, UC_DOC_BASE),
    },
    {
      type: 'category',
      label: 'Tutorials',
      link: {
        type: 'generated-index',
        description:
          'Learn how to leverage the power of the platform to build your own applications.',
      },
      items: [{ type: 'autogenerated', dirName: 'tutorials' }],
    },
    {
      type: 'category',
      label: 'Contribute',
      link: {
        type: 'generated-index',
        description:
          'There are many ways to contribute to the project. Find out how you can help!',
      },
      items: [{ type: 'autogenerated', dirName: 'contribute' }],
    },
  ],
};

export default sidebars;
